schemaVersion: 2.2.0
metadata:
  # Reusing the same name for a version is buggy. So we set `generatedName` instead of `name`.
  generateName: sas-devspaces-test
  version: 0.0.1
  description: DevSpaces SAS Test

commands:
  - id: configure-trusted-domains
    exec:
      component: devtools
      commandLine: |
        jq '.linkProtectionTrustedDomains |= .+ ["https://azureuse011258.my-trials.sas.com"]' \
            </checode/checode-linux-libc/ubi8/product.json >/tmp/product.json \
        && mv /tmp/product.json /checode/checode-linux-libc/ubi8/product.json || true
  - id: use-microsoft-marketplace
    exec:
      component: devtools
      commandLine: |
        jq '.extensionsGallery |= (.serviceUrl = $serviceUrl | .cacheUrl = $cacheUrl | .itemUrl = $itemUrl)' \
            --arg serviceUrl "https://marketplace.visualstudio.com/_apis/public/gallery" \
            --arg cacheUrl "https://vscode.blob.core.windows.net/gallery/index" \
            --arg itemUrl "https://marketplace.visualstudio.com/items" \
            </checode/checode-linux-libc/ubi8/product.json >/tmp/product.json \
        && mv /tmp/product.json /checode/checode-linux-libc/ubi8/product.json || true

components:
  - name: devtools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-d071837
      cpuRequest: "1"
      cpuLimit: "1"
      memoryRequest: "1Gi"
      memoryLimit: "1Gi"
      env:
        - name: VSCODE_DEFAULT_WORKSPACE
          value: .
        - name: HTTPS_PROXY
          value: ""
        - name: HTTP_PROXY
          value: ""
        - name: NO_PROXY
          value: ""

events:
  postStart:
    - configure-trusted-domains
    - use-microsoft-marketplace
